[plugin]
id = "cache-compiler-plugin"
class = "io.ballerina.stdlib.cache.compiler.CacheCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/cache-compiler-plugin-@project.version@.jar"
